// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrE37h6zr8K0pG9R3zmJwTQcgWjIQrjmE',
    appId: '1:909819415310:web:7570cbdc8899ed61e2255f',
    messagingSenderId: '909819415310',
    projectId: 'test1-59352',
    authDomain: 'test1-59352.firebaseapp.com',
    databaseURL: 'https://test1-59352-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test1-59352.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTkJuU7TAt5XpeCdz0TCo-OZY8fVv6Hqk',
    appId: '1:909819415310:android:d56b9fe7c729d771e2255f',
    messagingSenderId: '909819415310',
    projectId: 'test1-59352',
    databaseURL: 'https://test1-59352-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test1-59352.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP4y0s3OQHMxnu_1bJEYotPhfVBrf48Rk',
    appId: '1:909819415310:ios:7909aa7cea820741e2255f',
    messagingSenderId: '909819415310',
    projectId: 'test1-59352',
    databaseURL: 'https://test1-59352-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test1-59352.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP4y0s3OQHMxnu_1bJEYotPhfVBrf48Rk',
    appId: '1:909819415310:ios:7909aa7cea820741e2255f',
    messagingSenderId: '909819415310',
    projectId: 'test1-59352',
    databaseURL: 'https://test1-59352-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test1-59352.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrE37h6zr8K0pG9R3zmJwTQcgWjIQrjmE',
    appId: '1:909819415310:web:32ef72ddc9478a8fe2255f',
    messagingSenderId: '909819415310',
    projectId: 'test1-59352',
    authDomain: 'test1-59352.firebaseapp.com',
    databaseURL: 'https://test1-59352-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test1-59352.appspot.com',
  );
}
